#!/usr/bin/env bash
# script to display "To infinity and beyond" indefinitely , till killed with "ctrl+c", each iteration of the loop "sleep 2"is added
while true
do
echo "To infinity and beyond"
sleep 2
done
