#!/usr/bin/env bash
# script to display "To infinity and beyond" indefinitely, with a sleep 2 in between each iteration, and "I am invincible!!!" when receiving a SIGTERM

trap "echo I am invincible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
