#!/usr/bin/env bash
# script to display numbers from 1 to 100

for i in {1..100}
do
if ((1 % 15 == 0))
then
echo "FizzBuzz"
elif ((i % 5 == 0))
then
echo "Buzz"
elif ((i % 3 == 0))
then
echo "fizz"
else
echo "$i"
fi
done
