#!/usr/bin/env bash
# script to display "Best School", except for 4th iteration, display "bad luck" and for the 8th iteration display "good luck"
i=1
while [ $i -le 10 ]
do
if [ $i == 4 ]; then
echo "bad luck"
elif [ $i == 8 ]; then
echo "good luck"
else
echo "Best School"
fi
((i++))
done
