#!/usr/bin/env bash
# script to configure an Ubuntu server with, "localhost" resolves to "127.0.0.2" and "facebook.com" resolves to "8.8.8.8"

cp /etc/hosts ~/new.host
sed -i s/127.0.0.1/127.0.0.2/ ~/new.host
echo "8.8.8.8 facebook.com" >> ~/new.host
cp -f ~/new.host /etc/hosts
